version: '3.3'
 
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    environment:
        - POSTGRES_DB=authorizer
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=pg@123
    volumes:
      - pg-volume-data:/var/lib/postgresql/data
      
  redis:
    image: redis:6.0.10-alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.4.0
    depends_on:
      - elasticsearch
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
      - "./apm-server.yml:/usr/share/apm-server/apm-server.yml:ro"
    ports:
      - 8200:8200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  
volumes:
  pg-volume-data:
