version: '3.3'
 
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    environment:
        - POSTGRES_DB=authorizer
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=pg@123
    volumes:
      - pg-volume-data:/var/lib/postgresql/data
  
volumes:
  pg-volume-data:
